### ISSUE TITLE
Best way to use it with "shared-bus" crate

### ISSUE THREAD

**Issue by xtox-io** [pyaillet/ft6x36-rs#11]
What is the best way to make this compatible with https://docs.rs/shared-bus/0.3.1/shared_bus/ ?
A kind of proxy to implement I2c ?

**Comment by pyaillet** [comment]
Hi!
I have not used shared_bus with this device, but I used it with two other driver crates that I made. You can check it [there](https://github.com/pyaillet/twatch-idf-rs/blob/feb19a4da593ce90ac9a7f300caa35b4d2b10c34/src/twatch.rs#L124-L165).

On my side, I don't see any special problems with using this with the crate. However, I think that there are ways to solve the kind of problems related with shared_bus usage directly in [embedded-hal](https://docs.rs/embedded-hal-bus/latest/embedded_hal_bus/i2c/index.html).

Could you tell me more on your use case ?

**Comment by xtox-io** [comment]
Hi sorry for late reply, cause I was digging in for this problem :)

I'm keen on Rust but new on embedded programming with it.

I'm trying to use this driver with M5StackCoreS3 and the way I came along is;

- learned that I need to use https://github.com/georgik/aw9523-rs.git (thx alot to @georgik and your samples)
- shared_bus uses embedded-hal=0.2.0 and so does aw9523 library
- i ported down your driver ft6x36 to work with embedded-hal=0.2.0

but now when I see your samples for TWatch2020-V1 you are using an interrupt and not sure how to find it for M5StackCoreS3.

The docs https://docs.m5stack.com/en/core/CoreS3 talks about an interrupt(AW9523B_P1_2) on aw9523 extension here and trying to understand what that is :)

I would be appreciated if you help an amateur in embedded programming with Rust

**Comment by pyaillet** [comment]
Hi!

I'm not considering myself an expert on those subjects, so you should not take my advices for granted 😅 
However feel free to ask other questions if my explanations are not clear.

### Bypassing interrupts and polling

Interrupt handling is not mandatory, as a first approach, I would try using the "usual" loop with polling on the device. In which case, you would ignore the interrupt handling part of my code and just poll with `get_touch_event` and maybe `process_event` in the loop.

### Interrupts

If you want to use interrupts it would be a bit trickier:

If I understand correctly in your case the [FT6336 interrupt line is connected to a AW9523 GPIO](https://shop.m5stack.com/products/m5stack-cores3-esp32s3-lotdevelopment-kit).
But those pins are not exposed directly on the ESP32, you have to use the I2C bus to query or set them up. And rely [on the global AW9523 interrupt line](https://forums.adafruit.com/viewtopic.php?t=197181) to be notified when an interrupt occurs on a AW9523 pin that you setup correctly.

I guess setting all that is required for this would be:
- a dedicated driver to handle the AW9523
- setup the pin correctly and handling the interrupt correctly
I would check the C examples [here](https://github.com/adafruit/Adafruit_AW9523/blob/master/examples/ledbutton_demo/ledbutton_demo.ino) and [here](https://github.com/adafruit/Adafruit_AW9523/blob/master/Adafruit_AW9523.cpp).

**Comment by xtox-io** [comment]
I'm appreciated thanks a lot for the clue.
Will let you know if I can go further.

Regards :1st_place_medal:

**Comment by pyaillet** [comment]
You're welcome :)
I will close this for now, feel free to reopen it or an other issue if you have other questions.
