### ISSUE TITLE
FYI: Gestures might require additional firmware

### ISSUE THREAD

**Issue by JuliDi** [pyaillet/ft6x36-rs#12]
Apparently gestures require some sort of custom firmware: https://forums.adafruit.com/viewtopic.php?t=62697

And also ST's BSP example for the STM32F469I-DISCO board does not seem to use it, although their driver implements reading that register.

**Comment by pyaillet** [comment]
Thanks for the info.

I came to the same conclusion.

However, this driver provides some mechanism to identify multi-touch and swipe from a succession of `RawTouchEvent`.

**Comment by pyaillet** [comment]
I will close this for now, feel free to reopen it if you have other questions or new elements to add.
